#!/usr/bin/env python3
"""Regenerate re/foxhole/foxhole.s: tools/rdis.py over the section-2 code ($17000-$19020) with labels.txt
(finaljungle snapshot + foxhole overrides) and inline comments.txt; coverage = foxhole_cov.hist (+ finaljungle's
cov_all.hist if present). Foxhole-specific routines are tagged 'FOXHOLE' in their label comments."""
import subprocess, os, re
D = os.path.dirname(os.path.abspath(__file__)); R = os.path.dirname(os.path.dirname(D))
extra = ('172c2 17414 1741e 179fa 17c1e 17c32 17c7c 17cc6 17cfc 17e30 17e5e 18192 181b4 182b0 1833a '
         '1846c 184c6 18520 1857a 185d4 1862e 18688 18706 18718 18760 187a8 18804 1780a 179be').split()
covs = [f'{D}/foxhole_cov.hist']
fj = f'{R}/re/finaljungle/cov_all.hist'
if os.path.exists(fj):
    covs.append(fj)
cmd = ['python3', f'{R}/tools/rdis.py', f'{R}/re/dumps/ram_section2.bin', '17000', '19020', '--follow-hi', '18866',
       '--labels', f'{D}/labels.txt'] + sum([['--cov', c] for c in covs], []) + sum([['--entry', e] for e in extra], [])
txt = subprocess.run(cmd, capture_output=True, text=True, check=True).stdout
com = {}
for line in open(f'{D}/comments.txt'):
    line = line.rstrip('\n')
    if not line or line.startswith('#'):
        continue
    a, c = line.split(' ', 1)
    com[int(a, 16)] = c
out = []
for line in txt.split('\n'):
    m = re.match(r'^([0-9a-f]{6})  ', line)
    if m:
        a = int(m.group(1), 16)
        if a in com and ' ; ' + com[a] not in line:
            line = f'{line:<72} ; {com[a]}'
    out.append(line)
hdr = ('; Platoon (Amiga) load section 2 "THE JUNGLE & FOXHOLE" - listing for module re/foxhole\n'
       '; (the bunker/"foxhole" room with Sgt Barnes, grenades, win check and the ending screens).\n'
       '; Shared engine names come from re/finaljungle (snapshot in labels.txt); foxhole routines are tagged FOXHOLE.\n'
       '; generated by gen_listing.py (tools/rdis.py + labels.txt + comments.txt). Spec: NOTES.md.\n'
       '; RAM == ADF: A <-> ADF offset A + $81a00 (tracks $6f..$9e). Code $17000-$18865, data $18866-$193ff.\n')
open(f'{D}/foxhole.s', 'w').write(hdr + '\n'.join(out))
print('lines', len(out))
