#!/usr/bin/env python3
"""Regenerate re/flare/flare.s: rdis over section-1 code with flare labels, merge inline comments, keep flare scope."""
import subprocess, os, re
D = os.path.dirname(os.path.abspath(__file__)); R = os.path.dirname(os.path.dirname(D))
extra = '17a08 17ab4 17b0c 17b76 17ca6 187d6 18810 18862 18880 1888c 18898 188a4 188ba 188ce 188e6 188fc 1890c'.split()
cmd = ['python3', f'{R}/tools/rdis.py', f'{R}/re/dumps/ram_section1.bin', '17000', '1a100', '--follow-hi', '19374',
       '--cov', f'{R}/re/cov/section1.hist', '--labels', f'{D}/labels.txt'] + sum([['--entry', e] for e in extra], [])
cmd += ['--cov', f'{D}/flare_cov.hist']
txt = subprocess.run(cmd, capture_output=True, text=True, check=True).stdout
com = {}
for line in open(f'{D}/comments.txt'):
    line = line.rstrip('\n')
    if not line or line.startswith('#'): continue
    a, c = line.split(' ', 1); com[int(a, 16)] = c
SCOPE = [(0x17252, 0x17304, 'exits / text screens'), (0x17810, 0x178be, 'flare object lists'),
         (0x17dd0, 0x17e60, 'player hit (flare variant)'), (0x17e60, 0x17f7c, 'red fade / morale'),
         (0x17f7c, 0x18330, 'bob blits (normal + night)'), (0x18922, 0x1897a, 'tunnel exit -> flare'),
         (0x189c0, 0x19374, 'flare section core'), (0x19374, 0x19820, 'messages'), (0x19851, 0x199bc, 'text screens'),
         (0x19e0a, 0x1a0b2, 'flare objects/tables/palettes')]
out = []; keep = False
def inscope(a): return any(lo <= a < hi for lo, hi, _ in SCOPE)
cur = None
for line in txt.split('\n')[1:]:
    m = re.match(r'^([0-9a-f]{6})  ', line)
    if m:
        a = int(m.group(1), 16)
        keep = inscope(a)
        if keep:
            sec = [s for s in SCOPE if s[0] <= a < s[1]][0]
            if sec != cur:
                cur = sec; k = len(out)
                while k > 0 and (out[k-1].startswith('\x00') or out[k-1].strip() == ''): k -= 1
                out.insert(k, f'\n;======== {sec[2]}  ${sec[0]:05x}-${sec[1]:05x} ========')
            if a in com and ' ; ' + com[a] not in line: line = f'{line:<70} ; {com[a]}'
            out.append(line)
        else:
            out.append('\x01')
    elif line.strip() == '':
        if keep: out.append(line)
    else:
        # label line: keep if next instr in scope -> buffer
        out.append(('\x00' + line))
# drop label lines not followed by in-scope code
res = []
for i, l in enumerate(out):
    if l.startswith('\x00'):
        j = i + 1
        while j < len(out) and (out[j].startswith('\x00') or out[j].strip() == ''): j += 1
        if j < len(out) and re.match(r'^[0-9a-f]{6}  ', out[j]): res.append(l[1:])
    elif l != '\x01': res.append(l)
open(f'{D}/flare.s', 'w').write('; flare module annotated listing (generated by annotate.py from rdis + labels.txt + comments.txt)\n' + '\n'.join(res) + '\n')
print('ok', len(res))
