#!/bin/sh
# Savestate compatibility of the section-1 options: a run with a snapshot/restore round trip every K frames (fresh
# Machine) must be byte-identical (full-RAM hash every frame) to the uninterrupted run with the same options.
# Needs the scripts generated by s1test.py (run it first). usage: roundtrip.sh BIN [FTDIR]
BIN=$1; FT=${2:-/tmp/enh-section1/ft}; ADF=$(dirname $0)/../../../re/platoon_port.adf
OUT=/tmp/enh-section1/rt; mkdir -p $OUT; rc=0
t() { name=$1; frames=$2; enh=$3
  for mode in plain rt; do
    extra=""; [ $mode = rt ] && extra="--roundtrip-every 97"
    PLATOON_ENH="originalCredits=0,$enh" $BIN --adf $ADF --frames $frames --script $FT/$name/script.txt --out $OUT/$name-$mode \
      --deterministic --hash 0 80000 $extra 2>&1 | grep '^frame' > $OUT/$name-$mode.hash
  done
  n=$(grep -c . $OUT/$name-plain.hash)
  if [ "$n" -gt 0 ] && cmp -s $OUT/$name-plain.hash $OUT/$name-rt.hash; then echo "PASS $name ($n frames, $enh)"; else
    echo "FAIL $name ($enh)"; diff $OUT/$name-plain.hash $OUT/$name-rt.hash | head -3; rc=1; fi
}
t keep_on 1910 "s1.keepItems=1,s1.checkpointRespawn=1"
t flare_retry 3710 "s1.flareRetry=1"
t flare_keep 3710 "s1.keepItems=1"
t explored_on 1070 "s1.exploredMap=1"
t lives3 5010 "game.lives=3"
t rand_1 1010 "s1.randomSeed=1"
exit $rc
