#!/usr/bin/env python3
"""Regenerate re/audio/audio.s: rdis listing of $2800-$4310 (driver code + tables) from the disk-initial RAM image,
with labels.txt, the merged emulator coverage (coverage.hist) and inline comments from icomments.txt."""
import os, subprocess, sys
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
sys.path.insert(0, HERE)
from replayer import load_ram_from_adf
os.makedirs(os.path.join(HERE, 'work'), exist_ok=True)
ram = os.path.join(HERE, 'work', 'ram_disk.bin')
open(ram, 'wb').write(load_ram_from_adf(os.path.join(ROOT, 're/platoon_darc.adf')))
cmd = [sys.executable, os.path.join(ROOT, 'tools/rdis.py'), ram, '2800', '4310', '--cov', os.path.join(HERE, 'coverage.hist'),
       '--labels', os.path.join(HERE, 'labels.txt')]
for e in ('2800', '280e', '281c', '282a', '2838', '2846'): cmd += ['--entry', e]
raw = subprocess.run(cmd, capture_output=True, text=True, check=True).stdout
ic = {}
for l in open(os.path.join(HERE, 'icomments.txt')):
    l = l.rstrip('\n')
    if l.strip() and not l.startswith('#'):
        a, c = l.split(None, 1); ic[int(a, 16)] = c
out = ['; Platoon (Amiga, Ocean 1988) - David Whittaker music/sfx driver, RAM $2800-$430a (initial image from disk).',
       '; Generated by re/audio/mklisting.py (tools/rdis.py + labels.txt + icomments.txt). See re/audio/NOTES.md.', '']
for l in raw.splitlines():
    if len(l) > 8 and l[6:8] == '  ' and all(c in '0123456789abcdef' for c in l[:6]):
        a = int(l[:6], 16)
        if a in ic:
            l = l + ('  ; ' if ' ; ' not in l else ' | ') + ic[a]
    out.append(l)
open(os.path.join(HERE, 'audio.s'), 'w').write('\n'.join(out) + '\n')
print('wrote audio.s', len(out), 'lines')
