#!/usr/bin/env python3
# Builds re/kernel/kernel.s from the rdis part listings (see NOTES.md "Regenerating the listing").
import re, os
W = os.path.dirname(os.path.abspath(__file__))
parts = ['part1.s', 'part2.s', 'part3.s', 'part4.s']
hdr = """; ======================================================================================
; Platoon (Amiga, Ocean 1988) - kernel module annotated listing (resident $400-$2537,
; relocator $2538-$27ff, kernel $f800-$16a6b incl. data, boot loader $76000-$766ff).
; Generated by tools/rdis.py with re/kernel/labels.txt, then patched by re/kernel/work/mklisting.py.
; RAM image: chip-RAM dump taken in play (addresses = runtime addresses). See re/kernel/NOTES.md.
; NOTE capstone quirks fixed/flagged below:
;   * 'sbcd -(a1),-(a0)' ($8109) is mis-decoded by capstone as a 4-byte insn -> patched at $10f32/$10f3e.
;   * 'btst #n,d16(pc)' effective addresses printed 2 too low (e.g. $1748 really tests $24a4 = shift keys).
; ======================================================================================
"""
fix = {
 '010f32': ["010f32  8109                 sbcd     -(a1), -(a0)           ; $6d(a6) seconds -= 0+X (a1 -> zero byte $10fa9)",
            "010f34  64000014             bcc.w    vbl_common",
            "010f38  1d7c0059006d         move.b   #$59, $6d(a6)          ; seconds wrapped: 59",
            "010f3e  8109                 sbcd     -(a1), -(a0)           ; $6c(a6) minutes -= 0+X",
            "010f40  64000008             bcc.w    vbl_common"],
}
skip = set(['010f36', '010f3a', '010f3e', '010f42'])
out = [hdr]
for p in parts:
    out.append('\n; ---------------------------------------------------------------- %s\n' % p)
    for line in open(os.path.join(W, p)):
        a = line[:6]
        if a in fix:
            out.extend(x + '\n' for x in fix[a]); continue
        if a in skip: continue
        if a == '001748' or a == '001752':
            line = line.rstrip('\n') + '   ; really $24a4 (LSHIFT/RSHIFT byte)\n'
        out.append(line)
open(os.path.join(W, '..', 'kernel.s'), 'w').write(''.join(out))
print('wrote kernel.s', sum(1 for _ in open(os.path.join(W, '..', 'kernel.s'))), 'lines')
