// Section 0 variables (RAM $5f880-$60fe1, cleared at section start) and the kernel globals (a6 = $12dde)
// used by the section-0 code. All state stays in RAM at the original addresses (re/jungle/NOTES.md §c);
// these are just named accessors. GENERATED by a small script from the NOTES variable table.

/// Named accessors for the section-0 RAM variables.
struct S0Vars {
    let mem: Memory

    /// $5f880: player x (screen coords +16, always $94)
    var px: UInt16 { @inline(__always) get { mem.r16(0x5f880) } @inline(__always) nonmutating set { mem.w16(0x5f880, newValue) } }
    /// $5f882: player y ($50 ground, $3d inside a hut)
    var py: UInt16 { @inline(__always) get { mem.r16(0x5f882) } @inline(__always) nonmutating set { mem.w16(0x5f882, newValue) } }
    /// $5f884: player animation frame (index into frame table $1a1c6)
    var pframe: UInt16 { @inline(__always) get { mem.r16(0x5f884) } @inline(__always) nonmutating set { mem.w16(0x5f884, newValue) } }
    /// $5f886: player facing: 0 right, 1 left
    var pfacing: UInt16 { @inline(__always) get { mem.r16(0x5f886) } @inline(__always) nonmutating set { mem.w16(0x5f886, newValue) } }
    /// $5f888: enemy state 0..8 (table $1aad0)
    var estate: UInt16 { @inline(__always) get { mem.r16(0x5f888) } @inline(__always) nonmutating set { mem.w16(0x5f888, newValue) } }
    /// $5f88a: enemy x
    var ex: UInt16 { @inline(__always) get { mem.r16(0x5f88a) } @inline(__always) nonmutating set { mem.w16(0x5f88a, newValue) } }
    /// $5f88c: enemy y
    var ey: UInt16 { @inline(__always) get { mem.r16(0x5f88c) } @inline(__always) nonmutating set { mem.w16(0x5f88c, newValue) } }
    /// $5f88e: enemy frame (0 = invisible)
    var eframe: UInt16 { @inline(__always) get { mem.r16(0x5f88e) } @inline(__always) nonmutating set { mem.w16(0x5f88e, newValue) } }
    /// $5f890: enemy facing 0 right / 1 left
    var efacing: UInt16 { @inline(__always) get { mem.r16(0x5f890) } @inline(__always) nonmutating set { mem.w16(0x5f890, newValue) } }
    /// $5f892: enemy base frame / death counter / anim step
    var ebase: UInt16 { @inline(__always) get { mem.r16(0x5f892) } @inline(__always) nonmutating set { mem.w16(0x5f892, newValue) } }
    /// $5f894: enemy anim counter / fall speed / timer
    var ecnt: UInt16 { @inline(__always) get { mem.r16(0x5f894) } @inline(__always) nonmutating set { mem.w16(0x5f894, newValue) } }
    /// $5f896: enemy walk speed px/tick
    var espeed: UInt16 { @inline(__always) get { mem.r16(0x5f896) } @inline(__always) nonmutating set { mem.w16(0x5f896, newValue) } }
    /// $5f898: villager flag (st.b -> $ff00)
    var evillager: UInt16 { @inline(__always) get { mem.r16(0x5f898) } @inline(__always) nonmutating set { mem.w16(0x5f898, newValue) } }
    /// $5f89a: player state 0..10 (table $1aaa4)
    var pstate: UInt16 { @inline(__always) get { mem.r16(0x5f89a) } @inline(__always) nonmutating set { mem.w16(0x5f89a, newValue) } }
    /// $60c24: map column of the leftmost tile of the attribute window
    var T: UInt16 { @inline(__always) get { mem.r16(0x60c24) } @inline(__always) nonmutating set { mem.w16(0x60c24, newValue) } }
    /// $60c26: level 0..5 (map strip)
    var level: UInt16 { @inline(__always) get { mem.r16(0x60c26) } @inline(__always) nonmutating set { mem.w16(0x60c26, newValue) } }
    /// $60c28: player map column
    var pcol: UInt16 { @inline(__always) get { mem.r16(0x60c28) } @inline(__always) nonmutating set { mem.w16(0x60c28, newValue) } }
    /// $60c2a: copy of level (written with pcol as a long)
    var plevel: UInt16 { @inline(__always) get { mem.r16(0x60c2a) } @inline(__always) nonmutating set { mem.w16(0x60c2a, newValue) } }
    /// $60c2c: pointer to the bottom-row map byte at the player column
    var pmapptr: UInt32 { @inline(__always) get { mem.r32(0x60c2c) } @inline(__always) nonmutating set { mem.w32(0x60c2c, newValue) } }
    /// $60c30: player world x in 8-px units = T*8+c34+$1c
    var pworld: UInt16 { @inline(__always) get { mem.r16(0x60c30) } @inline(__always) nonmutating set { mem.w16(0x60c30, newValue) } }
    /// $60c32: hscroll & 7 (0 = player on an 8-px boundary)
    var align: UInt16 { @inline(__always) get { mem.r16(0x60c32) } @inline(__always) nonmutating set { mem.w16(0x60c32, newValue) } }
    /// $60c34: coarse scroll inside the tile, bytes, even, -6..+6
    var c34: UInt16 { @inline(__always) get { mem.r16(0x60c34) } @inline(__always) nonmutating set { mem.w16(0x60c34, newValue) } }
    /// $60c36: flip flag for draw_frame (+$40 frames)
    var flip: UInt16 { @inline(__always) get { mem.r16(0x60c36) } @inline(__always) nonmutating set { mem.w16(0x60c36, newValue) } }
    /// $60c38: facing saved during path/hut transitions
    var savefacing: UInt16 { @inline(__always) get { mem.r16(0x60c38) } @inline(__always) nonmutating set { mem.w16(0x60c38, newValue) } }
    /// $60c3a: path/hut walk offset
    var pathofs: UInt16 { @inline(__always) get { mem.r16(0x60c3a) } @inline(__always) nonmutating set { mem.w16(0x60c3a, newValue) } }
    /// $60c3c: player sub-counter
    var pcnt: UInt16 { @inline(__always) get { mem.r16(0x60c3c) } @inline(__always) nonmutating set { mem.w16(0x60c3c, newValue) } }
    /// $60c3e: toggled on each shot (unused)
    var firetoggle: UInt16 { @inline(__always) get { mem.r16(0x60c3e) } @inline(__always) nonmutating set { mem.w16(0x60c3e, newValue) } }
    /// $60c40: hut number 0..5 (door table index)
    var hut: UInt16 { @inline(__always) get { mem.r16(0x60c40) } @inline(__always) nonmutating set { mem.w16(0x60c40, newValue) } }
    /// $60c42: grenade in use
    var grenadeBusy: UInt16 { @inline(__always) get { mem.r16(0x60c42) } @inline(__always) nonmutating set { mem.w16(0x60c42, newValue) } }
    /// $60c44: world x delta this tick (-4/0/+4)
    var dx: UInt16 { @inline(__always) get { mem.r16(0x60c44) } @inline(__always) nonmutating set { mem.w16(0x60c44, newValue) } }
    /// $60c46: rifle cooldown
    var firecool: UInt16 { @inline(__always) get { mem.r16(0x60c46) } @inline(__always) nonmutating set { mem.w16(0x60c46, newValue) } }
    /// $60c66: grenade flight counter 8..0
    var grenadeT: UInt16 { @inline(__always) get { mem.r16(0x60c66) } @inline(__always) nonmutating set { mem.w16(0x60c66, newValue) } }
    /// $60c68: grenade-explosion frame 0..3
    var explFrame: UInt16 { @inline(__always) get { mem.r16(0x60c68) } @inline(__always) nonmutating set { mem.w16(0x60c68, newValue) } }
    /// $60c6a: grenade-explosion x
    var explX: UInt16 { @inline(__always) get { mem.r16(0x60c6a) } @inline(__always) nonmutating set { mem.w16(0x60c6a, newValue) } }
    /// $60c6c: grenade-explosion y
    var explY: UInt16 { @inline(__always) get { mem.r16(0x60c6c) } @inline(__always) nonmutating set { mem.w16(0x60c6c, newValue) } }
    /// $60c6e: grenade-explosion tick timer / active
    var explTimer: UInt16 { @inline(__always) get { mem.r16(0x60c6e) } @inline(__always) nonmutating set { mem.w16(0x60c6e, newValue) } }
    /// $60c70: hut-2 guard killed flag
    var hutKilled: UInt16 { @inline(__always) get { mem.r16(0x60c70) } @inline(__always) nonmutating set { mem.w16(0x60c70, newValue) } }
    /// $60c72: hut-1 trap-door prop x
    var hutPropX: UInt16 { @inline(__always) get { mem.r16(0x60c72) } @inline(__always) nonmutating set { mem.w16(0x60c72, newValue) } }
    /// $60c76: booby trap x
    var trapX: UInt16 { @inline(__always) get { mem.r16(0x60c76) } @inline(__always) nonmutating set { mem.w16(0x60c76, newValue) } }
    /// $60c7a: trap state 0 none / 1 armed / 2 exploding
    var trapState: UInt16 { @inline(__always) get { mem.r16(0x60c7a) } @inline(__always) nonmutating set { mem.w16(0x60c7a, newValue) } }
    /// $60c7c: explosives object x
    var bombX: UInt16 { @inline(__always) get { mem.r16(0x60c7c) } @inline(__always) nonmutating set { mem.w16(0x60c7c, newValue) } }
    /// $60c7e: explosives object y
    var bombY: UInt16 { @inline(__always) get { mem.r16(0x60c7e) } @inline(__always) nonmutating set { mem.w16(0x60c7e, newValue) } }
    /// $60c80: trap explosion frame
    var trapxFrame: UInt16 { @inline(__always) get { mem.r16(0x60c80) } @inline(__always) nonmutating set { mem.w16(0x60c80, newValue) } }
    /// $60c82: trap explosion tick timer
    var trapxTimer: UInt16 { @inline(__always) get { mem.r16(0x60c82) } @inline(__always) nonmutating set { mem.w16(0x60c82, newValue) } }
    /// $60c84: supply crate x
    var crateX: UInt16 { @inline(__always) get { mem.r16(0x60c84) } @inline(__always) nonmutating set { mem.w16(0x60c84, newValue) } }
    /// $60c86: supply crate y (0 = none)
    var crateY: UInt16 { @inline(__always) get { mem.r16(0x60c86) } @inline(__always) nonmutating set { mem.w16(0x60c86, newValue) } }
    /// $60c88: hit-test target x
    var hitTargetX: UInt16 { @inline(__always) get { mem.r16(0x60c88) } @inline(__always) nonmutating set { mem.w16(0x60c88, newValue) } }
    /// $60c8c: bullet old x
    var bulOldX: UInt16 { @inline(__always) get { mem.r16(0x60c8c) } @inline(__always) nonmutating set { mem.w16(0x60c8c, newValue) } }
    /// $60c90: bullet new x
    var bulNewX: UInt16 { @inline(__always) get { mem.r16(0x60c90) } @inline(__always) nonmutating set { mem.w16(0x60c90, newValue) } }
    /// $60c94: solid_at probe x
    var probeX: UInt16 { @inline(__always) get { mem.r16(0x60c94) } @inline(__always) nonmutating set { mem.w16(0x60c94, newValue) } }
    /// $60c96: solid_at probe y
    var probeY: UInt16 { @inline(__always) get { mem.r16(0x60c96) } @inline(__always) nonmutating set { mem.w16(0x60c96, newValue) } }
    /// $60c9c: bridge state: 0 intact, 1 charge set, 2 blown
    var bridge: UInt16 { @inline(__always) get { mem.r16(0x60c9c) } @inline(__always) nonmutating set { mem.w16(0x60c9c, newValue) } }
    /// $60c9e: man number shown highlighted on the choose screen
    var manHilite: UInt16 { @inline(__always) get { mem.r16(0x60c9e) } @inline(__always) nonmutating set { mem.w16(0x60c9e, newValue) } }
    /// $60ca0: invincible (cheat F5/F6)
    var invincible: UInt16 { @inline(__always) get { mem.r16(0x60ca0) } @inline(__always) nonmutating set { mem.w16(0x60ca0, newValue) } }
    /// $60ca4: runner shots fired 0..3
    var runnerShots: UInt16 { @inline(__always) get { mem.r16(0x60ca4) } @inline(__always) nonmutating set { mem.w16(0x60ca4, newValue) } }
    /// $60ca6: next bullet slot for runner shots
    var runnerSlot: UInt32 { @inline(__always) get { mem.r32(0x60ca6) } @inline(__always) nonmutating set { mem.w32(0x60ca6, newValue) } }
    /// $60caa: runner fire interval counter
    var runnerTimer: UInt16 { @inline(__always) get { mem.r16(0x60caa) } @inline(__always) nonmutating set { mem.w16(0x60caa, newValue) } }
    /// $60cae: enemy spawn chance / noise (7..$ff)
    var noise: UInt16 { @inline(__always) get { mem.r16(0x60cae) } @inline(__always) nonmutating set { mem.w16(0x60cae, newValue) } }
    /// $60cb0: pixel scroll counter 0..15
    var scrollcnt: UInt16 { @inline(__always) get { mem.r16(0x60cb0) } @inline(__always) nonmutating set { mem.w16(0x60cb0, newValue) } }
    /// $60cb2: hardware fine scroll (= scrollcnt)
    var hscroll: UInt16 { @inline(__always) get { mem.r16(0x60cb2) } @inline(__always) nonmutating set { mem.w16(0x60cb2, newValue) } }
    /// $60cb4: tick counter ($60cb7 bit0 = walk anim pacing)
    var tick: UInt32 { @inline(__always) get { mem.r32(0x60cb4) } @inline(__always) nonmutating set { mem.w32(0x60cb4, newValue) } }
    /// $60cba: foreground priority line y
    var prioLine: UInt16 { @inline(__always) get { mem.r16(0x60cba) } @inline(__always) nonmutating set { mem.w16(0x60cba, newValue) } }
    /// $60cbc: bridge-blast knock-back flag
    var blastflag: UInt8 { @inline(__always) get { mem.r8(0x60cbc) } @inline(__always) nonmutating set { mem.w8(0x60cbc, newValue) } }
    /// $60cbd: torch found (village)
    var torch: UInt8 { @inline(__always) get { mem.r8(0x60cbd) } @inline(__always) nonmutating set { mem.w8(0x60cbd, newValue) } }
    /// $60cbe: hut search latch
    var searchLatch: UInt8 { @inline(__always) get { mem.r8(0x60cbe) } @inline(__always) nonmutating set { mem.w8(0x60cbe, newValue) } }
    /// $60cbf: input at jump start
    var jumpInput: UInt8 { @inline(__always) get { mem.r8(0x60cbf) } @inline(__always) nonmutating set { mem.w8(0x60cbf, newValue) } }
    /// $60cc0: last horizontal direction bits
    var lastdir: UInt8 { @inline(__always) get { mem.r8(0x60cc0) } @inline(__always) nonmutating set { mem.w8(0x60cc0, newValue) } }
    /// $60cc1: input: b0 down b1 right b2 up b3 left b4 space b7 fire
    var input: UInt8 { @inline(__always) get { mem.r8(0x60cc1) } @inline(__always) nonmutating set { mem.w8(0x60cc1, newValue) } }
    /// $12dfc = current man record pointer $1e(a6)
    var manPtr: UInt32 { @inline(__always) get { mem.r32(0x12dfc) } @inline(__always) nonmutating set { mem.w32(0x12dfc, newValue) } }
    /// $12e00 = current man index $22(a6)
    var manIndex: UInt16 { @inline(__always) get { mem.r16(0x12e00) } @inline(__always) nonmutating set { mem.w16(0x12e00, newValue) } }
    /// $12e02 = map found $24(a6) (HUD icon)
    var mapFound: UInt16 { @inline(__always) get { mem.r16(0x12e02) } @inline(__always) nonmutating set { mem.w16(0x12e02, newValue) } }
    /// $12e06 = explosives carried $28(a6) (HUD icon)
    var explosives: UInt16 { @inline(__always) get { mem.r16(0x12e06) } @inline(__always) nonmutating set { mem.w16(0x12e06, newValue) } }
    /// $12e0c = morale $2e(a6)
    var morale: UInt16 { @inline(__always) get { mem.r16(0x12e0c) } @inline(__always) nonmutating set { mem.w16(0x12e0c, newValue) } }
    /// $12e26 = number of queued messages $48(a6)
    var msgCount: UInt16 { @inline(__always) get { mem.r16(0x12e26) } @inline(__always) nonmutating set { mem.w16(0x12e26, newValue) } }
    /// $12e38 = current upper palette pointer $5a(a6)
    var topPalPtr: UInt32 { @inline(__always) get { mem.r32(0x12e38) } @inline(__always) nonmutating set { mem.w32(0x12e38, newValue) } }
    /// $12e40 = back buffer $62(a6) ($70000 or $78000)
    var backBuf: UInt32 { @inline(__always) get { mem.r32(0x12e40) } @inline(__always) nonmutating set { mem.w32(0x12e40, newValue) } }
    /// $12e4e = cheat mode $70(a6)
    var cheat: UInt16 { @inline(__always) get { mem.r16(0x12e4e) } @inline(__always) nonmutating set { mem.w16(0x12e4e, newValue) } }
    /// $12e50 = BPLCON1 value for the playfield $72(a6)
    var bplcon1: UInt16 { @inline(__always) get { mem.r16(0x12e50) } @inline(__always) nonmutating set { mem.w16(0x12e50, newValue) } }
}

extension Platoon {
    /// Section-0 variable accessors.
    var v0: S0Vars { @inline(__always) get { S0Vars(mem: mem) } }
}
