#!/usr/bin/env python3
"""Regenerate re/finaljungle/finaljungle.s: rdis over the section-2 code with labels.txt, merge comments.txt."""
import subprocess, os, re
D = os.path.dirname(os.path.abspath(__file__)); R = os.path.dirname(os.path.dirname(D))
# object handlers reached only through pointers (tables / slot init / move.l #x,$a(a3))
extra = ('172c2 17414 1741e 179fa 17c1e 17c32 17c7c 17cc6 17cfc 17e30 17e5e 18192 181b4 182b0 1833a '
         '1846c 184c6 18520 1857a 185d4 1862e 18688 18706 18718 18760 187a8 18804 1780a 179be').split()
cmd = ['python3', f'{R}/tools/rdis.py', f'{R}/re/dumps/ram_section2.bin', '17000', '19020', '--follow-hi', '18866',
       '--cov', f'{D}/cov_all.hist', '--labels', f'{D}/labels.txt'] + sum([['--entry', e] for e in extra], [])
txt = subprocess.run(cmd, capture_output=True, text=True, check=True).stdout
com = {}
for line in open(f'{D}/comments.txt'):
    line = line.rstrip('\n')
    if not line or line.startswith('#'): continue
    a, c = line.split(' ', 1); com[int(a, 16)] = c
out = []
for line in txt.split('\n'):
    m = re.match(r'^([0-9a-f]{6})  ', line)
    if m:
        a = int(m.group(1), 16)
        if a in com and ' ; ' + com[a] not in line:
            line = f'{line:<72} ; {com[a]}'
    out.append(line)
hdr = ('; Platoon (Amiga) section 2 "THE JUNGLE & FOXHOLE" - final jungle + bunker/Barnes room (module re/finaljungle)\n'
       '; generated by gen_listing.py (tools/rdis.py + labels.txt + comments.txt). See NOTES.md for the spec.\n'
       '; RAM == ADF: A <-> ADF offset A + $81a00 (tracks 111..158). Code $17000-$18865, data $18866-$193ff.\n')
open(f'{D}/finaljungle.s', 'w').write(hdr + '\n'.join(out))
print('lines', len(out))
