import sys; sys.path.insert(0, '/tmp/verify-section0')
import plan
plan_mod = plan
P = plan.Planner('jungle_route', start_events=[(820, 'poke 60ca0 ff 1')], start_frame=830)
def go(l, c, d, v): P.go(l, c, d, v)
go(1, 13, 'right', 'down')
go(2, 19, 'right', 'down')
go(3, 26, 'right', 'down')
go(4, 31, 'right', 'up')
go(3, 30, 'left', 'up')
go(2, 33, 'right', 'down')
go(3, 34, 'right', 'down')
go(4, 46, 'right', 'up')
go(3, 48, 'right', 'down')
P.ev(0, 'right 1')
P.leg(lambda t: t['expl'] != 0, [(0, 'right 0')], label='EXPLOSIVES picked up')
P.save()
go(4, 48, 'left', 'up')
go(3, 46, 'left', 'down')
go(4, 34, 'left', 'up')
go(3, 33, 'left', 'up')
go(2, 30, 'left', 'down')
go(3, 31, 'right', 'down')
go(4, 6, 'left', 'up')
go(3, 4, 'left', 'up')
go(2, 3, 'left', 'up')
go(1, 4, 'right', 'up')
P.save()
go(0, 17, 'right', 'down')
go(1, 21, 'right', 'up')
go(0, 33, 'right', 'down')
go(1, 37, 'right', 'up')
go(0, 40, 'right', 'down')
go(1, 51, 'right', 'down')
go(2, 52, 'right', 'down')
go(3, 55, 'right', 'down')
go(4, 65, 'right', 'up')
go(3, 68, 'right', 'down')
go(4, 75, 'right', 'up')
go(3, 73, 'left', 'up')
go(2, 68, 'left', 'up')
P.save()
P.ev(0, 'right 1')
P.leg(lambda t: t['pst'] == 10, [(0, 'right 0')], label='PLANT (state 10)')
P.leg(lambda t: t['bridge'] == 2, [], label='BRIDGE BLOWN')
P.leg(lambda t: t['pst'] == 0, [], label='knock-back over')
go(1, 84, 'right', 'up')
P.save()
